Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\Automomation\Debugging\traceback_as_string.py", line 5, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
